import { msg } from "@lingui/core/macro";

export const Home = {
  HERO_TITLE: msg`Executive eCommerce Hub`,
  HERO_SUBTITLE: msg`Monitor live cross-channel revenue performance, evaluate ML-driven business recommendations, and explore operational fulfillment streams.`,
  HERO_BADGE: msg`The Look Analytics Platform`,
  HERO_BADGE_SUFFIX: msg`Analytics Platform`,
  ECOSYSTEM_CHECKOUT: msg`Checkout Stream`,
  ECOSYSTEM_INVENTORY: msg`Inventory Events`,
  ECOSYSTEM_SEMANTIC: msg`Looker Semantic AI`,
  ECOSYSTEM_FABRIC_SUFFIX: msg`Data Fabric`,
  ECOSYSTEM_REVENUE: msg`Live Revenue Hub`,
  ECOSYSTEM_AI_REC: msg`AI Recommendations`,
  ECOM_WIDGET_TITLE_SUFFIX: msg`Live Revenue Pulse`,
  ECOM_WIDGET_LIVE: msg`LIVE`,
  ECOM_WIDGET_TARGET: msg`+14.8% vs target`,
  ECOM_WIDGET_AOV_YIELD: msg`AOV Yield`,
  SECTION_KPI_TITLE: msg`Live Financial Summary`,
  KPI_REV_TITLE: msg`Total Revenue`,
  KPI_REV_BADGE: msg`+14.2% vs last month`,
  KPI_ORD_TITLE: msg`Total Orders`,
  KPI_ORD_BADGE: msg`+8.4% vs last month`,
  KPI_AOV_TITLE: msg`Average Order Value`,
  KPI_AOV_BADGE: msg`+5.1% target yield`,
  FALLBACK_SALES: msg`Sales Activity Stream`,
  FALLBACK_INSIGHTS: msg`AI Strategic Executive Briefing`,
  SECTION_APPS_TITLE: msg`Analytical Portals`,
  APP_DASH_TITLE: msg`Dashboard`,
  APP_DASH_DESC: msg`View embedded analytical dashboard reports and real-time business insights.`,
  APP_CA_TITLE: msg`Conversational Analytics`,
  APP_CA_DESC: msg`Interact with a conversational AI analytics assistant to query metrics.`,
  APP_AGENTS_TITLE: msg`Agents`,
  APP_AGENTS_DESC: msg`Manage and interact with Looker AI agents.`,
  APP_EXPLORE_TITLE: msg`Explore`,
  APP_EXPLORE_DESC: msg`Build and inspect visual queries, charts, and custom data filters on demand.`,
  APP_REPORT_TITLE: msg`Report Builder`,
  APP_REPORT_DESC: msg`Design personalized dashboard layouts, drag-and-drop elements, and templates.`,
  RESOURCE_TITLE: msg`Developer documentation`,
  RESOURCE_SUBTITLE: msg`Learn how to embed dashboards, build custom visualization extensions, and manage user attribute variables.`,
  RESOURCE_BTN: msg`Read Docs`,
};
