/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportViewerRouteImport } from './routes/report-viewer'
import { Route as ReportBuilderRouteImport } from './routes/report-builder'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversationalAnalyticsRouteImport } from './routes/conversational-analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const ReportViewerRoute = ReportViewerRouteImport.update({
  id: '/report-viewer',
  path: '/report-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportBuilderRoute = ReportBuilderRouteImport.update({
  id: '/report-builder',
  path: '/report-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationalAnalyticsRoute = ConversationalAnalyticsRouteImport.update({
  id: '/conversational-analytics',
  path: '/conversational-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/conversational-analytics': typeof ConversationalAnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/report-builder': typeof ReportBuilderRoute
  '/report-viewer': typeof ReportViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/conversational-analytics': typeof ConversationalAnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/report-builder': typeof ReportBuilderRoute
  '/report-viewer': typeof ReportViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/conversational-analytics': typeof ConversationalAnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/report-builder': typeof ReportBuilderRoute
  '/report-viewer': typeof ReportViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/conversational-analytics'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/report-builder'
    | '/report-viewer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/conversational-analytics'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/report-builder'
    | '/report-viewer'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/conversational-analytics'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/report-builder'
    | '/report-viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ConversationalAnalyticsRoute: typeof ConversationalAnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  ReportBuilderRoute: typeof ReportBuilderRoute
  ReportViewerRoute: typeof ReportViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report-viewer': {
      id: '/report-viewer'
      path: '/report-viewer'
      fullPath: '/report-viewer'
      preLoaderRoute: typeof ReportViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-builder': {
      id: '/report-builder'
      path: '/report-builder'
      fullPath: '/report-builder'
      preLoaderRoute: typeof ReportBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversational-analytics': {
      id: '/conversational-analytics'
      path: '/conversational-analytics'
      fullPath: '/conversational-analytics'
      preLoaderRoute: typeof ConversationalAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ConversationalAnalyticsRoute: ConversationalAnalyticsRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  ReportBuilderRoute: ReportBuilderRoute,
  ReportViewerRoute: ReportViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
